### ISSUE TITLE
env list not being freed

### ISSUE THREAD

**Issue by srondss** [Naji-k/minishell#34]
38 leaks.
env | wc = 38. 
Must be not freeing correctly.
![d9cea3d1-cb3b-40ae-9eb9-9e02f2c81490](https://github.com/Naji-k/minishell/assets/95218070/4a91f811-3713-44ed-9950-76e480175972)
![8aa00ca4-e1ac-48ed-8540-354a30a23822](https://github.com/Naji-k/minishell/assets/95218070/78388ad5-1ea4-405d-9ef2-57d08e322205)

**Comment by Naji-k** [comment]
fixed but still have LEAKS in min_cd

**Comment by Naji-k** [comment]
fixed LEAKS in mini_cd
