### ISSUE TITLE
echo ""asd

### ISSUE THREAD

**Issue by Naji-k** [Naji-k/minishell#76]
the output is:
`Printing Node:`
`Cmds: {echo}`
`Cmds: {}`
`Redirection: {0x0}.`
`Builtin: {echo}`
but it should be like 
`Printing Node:`
`Cmds: {echo}`
`Cmds: {}`
`Cmds: {asd}`
`Redirection: {0x0}.`
`Builtin: {echo}`

**Comment by srondss** [comment]
echo ""asd now gives:

```
Printing Node:
Cmds: {echo}
Cmds: {asd}
Redirection: {0x0}.
Builtin: {echo}
```

but you don't print anything? 
no output even though output should be asd.
