### ISSUE TITLE
only putting ~ in command will cause segfaults

### ISSUE THREAD

**Issue by srondss** [Naji-k/minishell#90]
double free error

**Comment by Naji-k** [comment]
There is a LEAKS if you do nothing. 
or if you run some commands and then exit, also there is a leak
<img width="570" alt="Screen Shot 2023-08-15 at 10 20 06 PM" src="https://github.com/Naji-k/minishell/assets/22378421/30988127-ee5a-4814-a3d6-7707fb3f37ea">

**Comment by srondss** [comment]
i will make PR soon which will fix this

**Comment by srondss** [comment]
PR #93 will fix leaks but still have problem with weird behaviour if only run ~ from executor side
